#subscriber-path: "console_subscriber.exe"
addr: "tcp://:50001"
benchmark:
  init:
    dataSourceName: "bucket:bucket123!@/vandelay"
  reps: 100
  seed: 1
  datapointValues:
      - name: DateAvailable
        value:  "2017-10-11"
      - name: ID
        value: 900
      - name: Name
        value: "bench 2"
      - name: Price
        value: 42.3
  shape:
    name: Test.Products
    keys:
      - ID
    properties:
      - name: DateAvailable
        type: date
      - name: ID
        type: integer
      - name: Name
        type: string
      - name: Price
        type: float
      